# -*- coding: utf-8 -*-
#
#----------------------------------------------------------------
#
#    VTDroid
#    Copyright (C) 2021  Nagoya Institute of Technology, Hiroki Inayoshi
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <https://www.gnu.org/licenses/>."
#
#----------------------------------------------------------------
#

bytecode = {
    'Z': [
        '  invoke-static {p0}, Ljava/lang/String;->valueOf(Z)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'I': [
        '  invoke-static {p0}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'C': [
        '  invoke-static {p0}, Ljava/lang/String;->valueOf(C)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'F': [
        '  invoke-static {p0}, Ljava/lang/String;->valueOf(F)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'S': [
        '  invoke-static {p0}, Ljava/lang/String;->valueOf(I)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'B': [
        '  const-string v0, "%02x"\n',
        '  const/4 v2, 0x1\n',
        '  new-array v2, v2, [Ljava/lang/Object;\n',
        '  const/4 v3, 0x0\n',
        '  and-int/lit16 p0, p0, 0xff\n',
        '  invoke-static {p0}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;\n',
        '  move-result-object p0\n',
        '  aput-object p0, v2, v3\n',
        '  invoke-static {v0, v2}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'J': [
        '  invoke-static {p0, p1}, Ljava/lang/String;->valueOf(J)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'D': [
        '  invoke-static {p0, p1}, Ljava/lang/String;->valueOf(D)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    '[Z': [
        '  new-instance v0, Ljava/lang/StringBuilder;\n',
        '  invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n',
        '  const/4 v2, 0x0\n',
        '  :goto_1\n',
        '  array-length v3, p0\n',
        '  if-ge v2, v3, :cond_0\n',
        '  aget-boolean v3, p0, v2\n',
        '  invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(Z)Ljava/lang/StringBuilder;\n',
        '  add-int/lit8 v2, v2, 0x1\n',
        '  goto :goto_1\n',
        '  :cond_0\n',
        '  invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    '[B': [
        '  new-instance v0, Ljava/lang/StringBuilder;\n',
        '  invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n',
        '  array-length v2, p0\n',
        '  const/4 v3, 0x0\n',
        '  :goto_1\n',
        '  if-ge v3, v2, :cond_0\n',
        '  aget-byte v4, p0, v3\n',
        '  const/4 v6, 0x1\n',
        '  new-array v6, v6, [Ljava/lang/Object;\n',
        '  and-int/lit16 v4, v4, 0xff\n',
        '  invoke-static {v4}, Ljava/lang/Integer;->valueOf(I)Ljava/lang/Integer;\n',
        '  move-result-object v4\n',
        '  const/4 v5, 0x0\n',
        '  aput-object v4, v6, v5\n',
        '  const-string v5, "%02x"\n',
        '  invoke-static {v5, v6}, Ljava/lang/String;->format(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;\n',
        '  move-result-object v5\n',
        '  invoke-virtual {v0, v5}, Ljava/lang/StringBuilder;->append(Ljava/lang/String;)Ljava/lang/StringBuilder;\n',
        '  add-int/lit8 v3, v3, 0x1\n',
        '  goto :goto_1\n',
        '  :cond_0\n',
        '  invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    '[S': [
        '  new-instance v0, Ljava/lang/StringBuilder;\n',
        '  invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n',
        '  const/4 v2, 0x0\n',
        '  :goto_1\n',
        '  array-length v3, p0\n',
        '  if-ge v2, v3, :cond_0\n',
        '  aget-short v3, p0, v2\n',
        '  invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;\n',
        '  add-int/lit8 v2, v2, 0x1\n',
        '  goto :goto_1\n',
        '  :cond_0\n',
        '  invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    '[C': [
        '  new-instance v0, Ljava/lang/String;\n',
        '  invoke-direct {v0, p0}, Ljava/lang/String;-><init>([C)V\n',
    ],
    '[I': [
        '  new-instance v0, Ljava/lang/StringBuilder;\n',
        '  invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n',
        '  const/4 v2, 0x0\n',
        '  :goto_1\n',
        '  array-length v3, p0\n',
        '  if-ge v2, v3, :cond_0\n',
        '  aget v3, p0, v2\n',
        '  invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(I)Ljava/lang/StringBuilder;\n',
        '  add-int/lit8 v2, v2, 0x1\n',
        '  goto :goto_1\n',
        '  :cond_0\n',
        '  invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    '[J': [
        '  new-instance v0, Ljava/lang/StringBuilder;\n',
        '  invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n',
        '  const/4 v2, 0x0\n',
        '  :goto_1\n',
        '  array-length v3, p0\n',
        '  if-ge v2, v3, :cond_0\n',
        '  aget-wide v3, p0, v2\n',
        '  invoke-virtual {v0, v3, v4}, Ljava/lang/StringBuilder;->append(J)Ljava/lang/StringBuilder;\n',
        '  add-int/lit8 v2, v2, 0x1\n',
        '  goto :goto_1\n',
        '  :cond_0\n',
        '  invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    '[F': [
        '  new-instance v0, Ljava/lang/StringBuilder;\n',
        '  invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n',
        '  const/4 v2, 0x0\n',
        '  :goto_1\n',
        '  array-length v3, p0\n',
        '  if-ge v2, v3, :cond_0\n',
        '  aget v3, p0, v2\n',
        '  invoke-virtual {v0, v3}, Ljava/lang/StringBuilder;->append(F)Ljava/lang/StringBuilder;\n',
        '  add-int/lit8 v2, v2, 0x1\n',
        '  goto :goto_1\n',
        '  :cond_0\n',
        '  invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    '[D': [
        '  new-instance v0, Ljava/lang/StringBuilder;\n',
        '  invoke-direct {v0}, Ljava/lang/StringBuilder;-><init>()V\n',
        '  const/4 v2, 0x0\n',
        '  :goto_1\n',
        '  array-length v3, p0\n',
        '  if-ge v2, v3, :cond_0\n',
        '  aget-wide v3, p0, v2\n',
        '  invoke-virtual {v0, v3, v4}, Ljava/lang/StringBuilder;->append(D)Ljava/lang/StringBuilder;\n',
        '  add-int/lit8 v2, v2, 0x1\n',
        '  goto :goto_1\n',
        '  :cond_0\n',
        '  invoke-virtual {v0}, Ljava/lang/StringBuilder;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    '[Ljava/lang/String;': [
        '  new-instance v0, Ljava/lang/StringBuffer;\n',
        '  invoke-direct {v0}, Ljava/lang/StringBuffer;-><init>()V\n',
        '  const/16 v2, 0x5b\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;\n',
        '  const/4 v3, 0x0\n',
        '  array-length v2, p0\n',
        '  if-ge v3, v2, :cond_1\n',
        '  const/16 v2, 0x27\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;\n',
        '  aget-object v2, p0, v3\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;\n',
        '  add-int/lit8 v3, v3, 0x1\n',
        '  :goto_1\n',
        '  array-length v2, p0\n',
        '  if-ge v3, v2, :cond_0\n',
        '  const/16 v2, 0x27\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;\n',
        '  const/16 v2, 0x2c\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;\n',
        '  const/16 v2, 0x27\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;\n',
        '  aget-object v2, p0, v3\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(Ljava/lang/String;)Ljava/lang/StringBuffer;\n',
        '  add-int/lit8 v3, v3, 0x1\n',
        '  goto :goto_1\n',
        '  :cond_0\n',
        '  const/16 v2, 0x27\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;\n',
        '  :cond_1\n',
        '  const/16 v2, 0x5d\n',
        '  invoke-virtual {v0, v2}, Ljava/lang/StringBuffer;->append(C)Ljava/lang/StringBuffer;\n',
        '  invoke-virtual {v0}, Ljava/lang/StringBuffer;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
        '  check-cast v0, Ljava/lang/String;\n',
    ],
    #'[Ljava/lang/String;': [
    #  '  invoke-static {p0}, Ljava/util/Arrays;->stream([Ljava/lang/Object;)Ljava/util/stream/Stream;\n',
    #  '  move-result-object v0\n',
    #  '  invoke-static {}, Ljava/util/stream/Collectors;->joining()Ljava/util/stream/Collector;\n',
    #  '  move-result-object v2\n',
    #  '  invoke-interface {v0, v2}, Ljava/util/stream/Stream;->collect(Ljava/util/stream/Collector;)Ljava/lang/Object;\n',
    #  '  move-result-object v0\n',
    #  '  check-cast v0, Ljava/lang/String;\n',
    #],
    'Ljava/lang/String;': [
        '  move-object v0, p0\n',
    ],
    'Ljava/lang/CharSequence;': [
        '  invoke-virtual {p0}, Ljava/lang/CharSequence;->toString()Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'String.valueOf(Object)': [
        '  invoke-static {p0}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'Landroid/text/Editable;': [
        '  invoke-static {p0}, Ljava/lang/String;->valueOf(Ljava/lang/Object;)Ljava/lang/String;\n',
        '  move-result-object v0\n',
    ],
    'serialization': [
        '  new-instance v0, Ljava/io/ByteArrayOutputStream;\n',
        '  invoke-direct {v0}, Ljava/io/ByteArrayOutputStream;-><init>()V\n',
        '  :try_start_0\n',
        '  new-instance v2, Ljava/io/ObjectOutputStream;\n',
        '  invoke-direct {v2, v0}, Ljava/io/ObjectOutputStream;-><init>(Ljava/io/OutputStream;)V\n',
        '  invoke-interface {v2, p0}, Ljava/io/ObjectOutput;->writeObject(Ljava/lang/Object;)V\n',
        '  invoke-interface {v2}, Ljava/io/ObjectOutput;->flush()V\n',
        '  invoke-virtual {v0}, Ljava/io/ByteArrayOutputStream;->toByteArray()[B\n',
        '  move-result-object v2\n',
        '  :try_end_0\n',
        '  .catch Ljava/io/IOException; {:try_start_0 .. :try_end_0} :catch_0\n',
        '  new-instance v0, Ljava/lang/String;\n',
        '  invoke-direct {v0, v2}, Ljava/lang/String;-><init>([B)V\n',
        '  invoke-static {v1, v0}, LSmalienWriter;->writeVal(Ljava/lang/String;Ljava/lang/String;)V\n',
        '  goto :goto_0\n',
        '  :catch_0\n',
        '  move-exception v1\n',
        '  :try_start_1\n',
        '  invoke-virtual {v0}, Ljava/io/ByteArrayOutputStream;->close()V\n',
        '  :try_end_1\n',
        '  .catch Ljava/io/IOException; {:try_start_1 .. :try_end_1} :catch_1\n',
        '  goto :goto_0\n',
        '  :catch_1\n',
        '  move-exception v1\n',
        '  :goto_0\n',
        '  return-void\n',
        '.end method\n\n',
    ],
    'footer_tag': [
        '  invoke-static {v0}, LSmalienWriter;->writeTag(Ljava/lang/String;)V\n'
        '  return-void\n',
        '.end method\n\n',
    ],
    'footer_val': [
        '  invoke-static {v1, v0}, LSmalienWriter;->writeVal(Ljava/lang/String;Ljava/lang/String;)V\n',
        '  :try_end_0\n',
        '  .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0\n',
        '  goto :goto_0\n',
        '  :catch_0\n',
        '  move-exception v2\n',
        '  :goto_0\n',
        '  nop\n',
        '  return-void\n',
        '.end method\n\n',
    ],
    'footer_val_barray': [
        '  invoke-static {v1, v0}, LSmalienWriter;->writeVal(Ljava/lang/String;Ljava/lang/String;)V\n',
        '  return-void\n',
        '.end method\n\n',
    ],
    # For Threads
    'tid_field_define': [
        '# instance fields\n',
        '.field public SmalienTID:I\n',
    ],
    # System Command Logging
    'system_command_logging': [
        '    invoke-static {p0, v0}, LSmalienWriter;->handle([Ljava/lang/String;Ljava/lang/String;)V\n',
        '    return-void\n',
        '.end method\n',
    ],
}
